-- MySQL Script generated by MySQL Workbench
-- Sun Sep  8 10:40:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema appcuestionarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appcuestionarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appcuestionarios` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `appcuestionarios` ;

-- -----------------------------------------------------
-- Table `appcuestionarios`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`subjects` (
  `subject_code` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `course` INT NOT NULL,
  `questions_per_test` INT NOT NULL,
  PRIMARY KEY (`subject_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`questions` (
  `id` VARCHAR(20) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `text` VARCHAR(250) NOT NULL,
  `default_grade` FLOAT NOT NULL,
  `penalty` FLOAT NOT NULL,
  `single` TINYINT(1) NULL DEFAULT NULL,
  `shuffle` TINYINT(1) NULL DEFAULT NULL,
  `subject_code` VARCHAR(20) NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_subjects` (`subject_code` ASC) VISIBLE,
  CONSTRAINT `fk_questions_subjects`
    FOREIGN KEY (`subject_code`)
    REFERENCES `appcuestionarios`.`subjects` (`subject_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`answers` (
  `id` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `question_id` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `text` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `fraction` FLOAT NOT NULL,
  `subject_code` VARCHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `content` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `score_fraction` FLOAT NULL DEFAULT NULL,
  `penalty_fraction` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `question_id`),
  INDEX `fk_answers_questions` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions`
    FOREIGN KEY (`question_id`)
    REFERENCES `appcuestionarios`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`users` (
  `user_id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `role` ENUM('alumno', 'profesor', 'administrador') NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `change_pass` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `mail` (`mail` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`test_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`test_attempts` (
  `id` BIGINT NOT NULL,
  `user` VARCHAR(10) NOT NULL,
  `subject` VARCHAR(30) NOT NULL,
  `content` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `score` FLOAT NULL DEFAULT NULL,
  `correct` INT NULL DEFAULT NULL,
  `incorrect` INT NULL DEFAULT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_test_attempts_users` (`user` ASC) VISIBLE,
  INDEX `fk_test_attempts_subjects` (`subject` ASC) VISIBLE,
  CONSTRAINT `fk_test_attempts_subjects`
    FOREIGN KEY (`subject`)
    REFERENCES `appcuestionarios`.`subjects` (`subject_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_test_attempts_users`
    FOREIGN KEY (`user`)
    REFERENCES `appcuestionarios`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`attempt_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`attempt_answers` (
  `attempt_id` BIGINT NOT NULL,
  `answer_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`attempt_id`, `answer_id`),
  INDEX `fk_attempt_answers_answers` (`answer_id` ASC) VISIBLE,
  CONSTRAINT `fk_attempt_answers_answers`
    FOREIGN KEY (`answer_id`)
    REFERENCES `appcuestionarios`.`answers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attempt_answers_test_attempts`
    FOREIGN KEY (`attempt_id`)
    REFERENCES `appcuestionarios`.`test_attempts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`attempt_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`attempt_questions` (
  `attempt_id` BIGINT NOT NULL,
  `question_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`attempt_id`, `question_id`),
  INDEX `fk_attempt_questions_questions` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_attempt_questions_questions`
    FOREIGN KEY (`question_id`)
    REFERENCES `appcuestionarios`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attempt_questions_test_attempts`
    FOREIGN KEY (`attempt_id`)
    REFERENCES `appcuestionarios`.`test_attempts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`nodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`nodes` (
  `subject_code` VARCHAR(10) NOT NULL,
  `nodeID` INT NOT NULL,
  PRIMARY KEY (`subject_code`, `nodeID`),
  CONSTRAINT `fk_nodes_subjects`
    FOREIGN KEY (`subject_code`)
    REFERENCES `appcuestionarios`.`subjects` (`subject_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`attributes` (
  `subject_code` VARCHAR(10) NOT NULL,
  `nodeID` INT NOT NULL,
  `attribute` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subject_code`, `nodeID`, `attribute`),
  CONSTRAINT `fk_attributes_nodes`
    FOREIGN KEY (`subject_code` , `nodeID`)
    REFERENCES `appcuestionarios`.`nodes` (`subject_code` , `nodeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`children`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`children` (
  `subject_code` VARCHAR(10) NOT NULL,
  `nodeID` INT NOT NULL,
  `childID` INT NOT NULL,
  PRIMARY KEY (`subject_code`, `nodeID`, `childID`),
  CONSTRAINT `fk_children_nodes`
    FOREIGN KEY (`subject_code` , `nodeID`)
    REFERENCES `appcuestionarios`.`nodes` (`subject_code` , `nodeID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`sessionids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`sessionids` (
  `sessionid` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(10) NULL DEFAULT NULL,
  `login_time` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`sessionid`),
  INDEX `fk_sessionids_users` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_sessionids_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `appcuestionarios`.`users` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`user_subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`user_subjects` (
  `user_id` VARCHAR(10) NOT NULL,
  `subject_code` VARCHAR(10) NOT NULL,
  `current_node` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `subject_code`),
  INDEX `user_subjects_ibfk_2` (`subject_code` ASC) VISIBLE,
  CONSTRAINT `user_subjects_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `appcuestionarios`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_subjects_ibfk_2`
    FOREIGN KEY (`subject_code`)
    REFERENCES `appcuestionarios`.`subjects` (`subject_code`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `appcuestionarios`.`visited_nodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appcuestionarios`.`visited_nodes` (
  `subject_code` VARCHAR(10) NOT NULL,
  `user_id` VARCHAR(10) NOT NULL,
  `nodeID` INT NOT NULL,
  PRIMARY KEY (`subject_code`, `user_id`, `nodeID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
